name: CI (master)

on:
  push:
    branches:
      - master

concurrency:
  group: master-ci
  cancel-in-progress: true

jobs:
  call-template:
    uses: ./.github/workflows/template_ci.yml
    with:
      projects: "FastMoq.Tests/FastMoq.Tests.csproj FastMoq.Tests.Web/FastMoq.Tests.Web.csproj"
      frameworks: '["8.0.x","9.0.x"]'
