name: CI (PR)

on:
  pull_request:
    branches:
      - master

jobs:
  call-template:
    uses: ./.github/workflows/template_ci.yml
    with:
      projects: "FastMoq.Tests/FastMoq.Tests.csproj FastMoq.Tests.Web/FastMoq.Tests.Web.csproj"
      frameworks: '["8.0.x","9.0.x"]'
