name: CI (PR)

on:
  pull_request:
    branches:
      - master
    paths:
      - .github/workflows/ci_pr.yml
      - FastMoq/
      - FastMoq.Core/
      - FastMoq.Web/
      - FastMoq.Tests/
      - FastMoq.Tests.Web/

jobs:
  call-template:
    uses: ./.github/workflows/template_ci.yml
    with:
      projects: "FastMoq.Tests/FastMoq.Tests.csproj FastMoq.Tests.Web/FastMoq.Tests.Web.csproj"
      frameworks: '["8.0.x","9.0.x"]'
