name: pr_FastMoq
on:
  workflow_call:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master # Release branch
    paths:
      - .github/workflows/pr_FastMoq.yml
      - FastMoq/
      - FastMoq.Core/
      - FastMoq.Web/
      - FastMoq.Tests/
      - FastMoq.Tests.Web/

jobs:
  codeql:
    uses: ./.github/workflows/codeql.yml

  test:
    needs: codeql
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
            fetch-depth: 0
      - name: Setup .NET 8.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Setup .NET 9.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Install dependencies
        run: dotnet restore FastMoq.Tests/FastMoq.Tests.csproj && dotnet restore FastMoq.Tests.Web/FastMoq.Tests.Web.csproj
      - name: Build .NET 8.0
        run: dotnet build FastMoq.Tests/FastMoq.Tests.csproj --framework net8.0 -p:SuppressTfmSupportBuildErrors=true && dotnet build FastMoq.Tests.Web/FastMoq.Tests.Web.csproj --framework net8.0 -p:SuppressTfmSupportBuildErrors=true
      - name: Build .NET 9.0  
        run: dotnet build FastMoq.Tests/FastMoq.Tests.csproj --framework net9.0 -p:SuppressTfmSupportBuildErrors=true && dotnet build FastMoq.Tests.Web/FastMoq.Tests.Web.csproj --framework net9.0 -p:SuppressTfmSupportBuildErrors=true
      - name: Test FastMoq.Tests .NET 8.0
        run: dotnet test FastMoq.Tests/FastMoq.Tests.csproj --framework net8.0 --no-build
      - name: Test FastMoq.Tests .NET 9.0
        run: dotnet test FastMoq.Tests/FastMoq.Tests.csproj --framework net9.0 --no-build
      - name: Test FastMoq.Tests.Web .NET 8.0
        run: dotnet test FastMoq.Tests.Web/FastMoq.Tests.Web.csproj --framework net8.0 --no-build
      - name: Test FastMoq.Tests.Web .NET 9.0
        run: dotnet test FastMoq.Tests.Web/FastMoq.Tests.Web.csproj --framework net9.0 --no-build
