name: pr_FastMoq
on:
  workflow_call:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master # Release branch
    paths:
      - .github/workflows/pr_FastMoq.yml
      - FastMoq/
      - FastMoq.Core/
      - FastMoq.Web/
      - FastMoq.Tests/
      - FastMoq.Tests.Web/

jobs:
  codeql:
    uses: ./.github/workflows/codeql.yml

  test:
    needs: codeql
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
            fetch-depth: 0
      - name: Setup .NET 6.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Setup .NET 8.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - name: Setup .NET 9.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x
      - name: Install dependencies
        run: dotnet restore FastMoq.Tests/FastMoq.Tests.csproj && dotnet restore FastMoq.Tests.Web/FastMoq.Tests.Web.csproj
      - name: Build
        run: dotnet build FastMoq.Tests/FastMoq.Tests.csproj && dotnet build FastMoq.Tests.Web/FastMoq.Tests.Web.csproj
      - name: Test FastMoq.Tests
        run: dotnet test FastMoq.Tests/FastMoq.Tests.csproj
      - name: Test FastMoq.Tests.Web
        run: dotnet test FastMoq.Tests.Web/FastMoq.Tests.Web.csproj
