name: pr_FastMoq
on:
  workflow_call:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master # Release branch
    paths:
      - .github/workflows/pr_FastMoq.yml
      - FastMoq/
      - FastMoq.Core/
      - FastMoq.Web/
      - FastMoq.Tests/
      - FastMoq.Tests.Web/
      - FastMoq.Tests.Blazor/
      - FastMoq.TestingExample/

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 9.0.x
      - name: Install dependencies
        run: dotnet restore FastMoq.sln
      - name: Build
        run: dotnet build FastMoq.sln
      - name: Test
        run: dotnet test FastMoq.sln