name: publish to nuget
on:
  push:
    branches:
      - master # Default release branch
    paths:
      - FastMoq/**
      - FastMoq.Core/**
      - FastMoq.Web/**
      - .github/workflows/publish_FastMoq.yml
      
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
          
      # Publish
      - name: Build FastMoq Web
        run: dotnet build

      - name: Creating a package
        run: dotnet pack -o .

      #- name: Publish to Nuget 
      #  run: dotnet nuget push *.nupkg -s https://api.nuget.org/v3/index.json -k ${{secrets.NUGET_API_KEY}} --skip-duplicate -n 
