name: CI Template

on:
  workflow_call:
    inputs:
      projects:
        required: true
        type: string
      frameworks:
        required: true
        type: string

jobs:
  codeql:
    uses: ./.github/workflows/codeql.yml

  build-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        framework: ${{ fromJSON(inputs.frameworks) }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.framework }}

      - run: dotnet --info

      - name: Restore
        run: |
          for proj in ${{ inputs.projects }}; do
            dotnet restore "$proj"
          done

      - name: Build
        env:
          FW: ${{ matrix.framework }}
        run: |
          tfm="net${FW%.*}"   # Bash trims .x or prerelease suffix
          for proj in ${{ inputs.projects }}; do
            dotnet build "$proj" --framework "$tfm"
          done

      - name: Test
        env:
          FW: ${{ matrix.framework }}
        run: |
          tfm="net${FW%.*}"
          for proj in ${{ inputs.projects }}; do
            dotnet test "$proj" --framework "$tfm" --no-build
          done
